import { attribute, autoGeneratedHashKey, table } from "@nova-odm/annotations";
import { BaseModel } from "../base-model-and-dao/base-model";


export enum WhatsAppChatSessionStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE"
}

export const PHONE_NUMBER_STATUS_INDEX = "phone-number-status-index";

export enum WhatsAppChatMessageSender {
    USER = "USER",
    BOT = "BOT"
}

@table("WhatsAppChatMessage")
export class WhatsAppChatMessage {
    @attribute()
    messageId: string;

    @attribute()
    message: string;

    @attribute()
    contextMessageId: string;

    @attribute()
    sender: WhatsAppChatMessageSender

    @attribute({
        type: "Date",
        defaultProvider: () => new Date()
    })
    sentAt: Date;

    @attribute({
        type: "Date"
    })
    deliveredAt?: Date;

    @attribute({
        type: "Date"
    })
    readAt?: Date;

}

export class WhatsAppChatHistory {
    @attribute()
    prompt: string;

    @attribute()
    messages: WhatsAppChatMessage[];
}

@table("WhatsAppChatSession")
export class WhatsAppChatSessionModel extends BaseModel{
    @autoGeneratedHashKey()
    sessionId: string;

    @attribute({
        type: "String",
        indexKeyConfigurations: {
            [PHONE_NUMBER_STATUS_INDEX]: "HASH"
        }
    })
    phoneNumber: string;

    @attribute({
        type: "String",
        indexKeyConfigurations: {
            [PHONE_NUMBER_STATUS_INDEX]: "RANGE"
        }
    })
    chatSessionStatus: WhatsAppChatSessionStatus

    @attribute({
        defaultProvider: () => {
            return {
                prompt: "",
                messages: []
            }
        }
    })
    chatHistory: WhatsAppChatHistory



    getLatestMessage(): WhatsAppChatMessage {
        if (this.chatHistory.messages.length === 0) {
            throw new Error("Chat history is empty");
        }
        return this.chatHistory.messages[this.chatHistory.messages.length - 1];
    }

    getSessionPrompt(): string {
        return this.chatHistory.prompt;
    }

    markSessionInactive(): void {
        this.chatSessionStatus = WhatsAppChatSessionStatus.INACTIVE;
    }
}