import { attribute, autoGeneratedHashKey, table } from "@nova-odm/annotations";
import { BaseModel } from "../base-model-and-dao/base-model";


export enum WhatsAppChatSessionStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE"
}

export const PHONE_NUMBER_STATUS_INDEX = "phone-number-status-index";
export const WHATSAPP_CHAT_SESSION_TABLE = "WhatsAppChatSession";

export enum WhatsAppChatMessageSender {
    USER = "USER",
    BOT = "BOT"
}

export class WhatsAppChatMessage {
    @attribute()
    messageId: string;

    @attribute()
    message: string;

    @attribute()
    contextMessageId?: string;

    @attribute()
    sender: WhatsAppChatMessageSender

    @attribute({
        type: "Date"
    })
    sentAt?: Date;

    @attribute({
        type: "Date"
    })
    deliveredAt?: Date;

    @attribute({
        type: "Date"
    })
    readAt?: Date;

    constructor(whatsAppChatMessage?: WhatsAppChatMessage) {
        if (whatsAppChatMessage) {
            Object.assign(this, whatsAppChatMessage);
        }
    }
}

export class WhatsAppChatHistory {
    @attribute()
    prompt: string;

    @attribute()
    messages: WhatsAppChatMessage[];
}

@table(WHATSAPP_CHAT_SESSION_TABLE)
export class WhatsAppChatSessionModel extends BaseModel{
    @autoGeneratedHashKey()
    sessionId: string;

    @attribute({
        type: "String",
        indexKeyConfigurations: {
            [PHONE_NUMBER_STATUS_INDEX]: "HASH"
        }
    })
    phoneNumber: string;

    @attribute({
        type: "String",
        indexKeyConfigurations: {
            [PHONE_NUMBER_STATUS_INDEX]: "RANGE"
        }
    })
    chatSessionStatus: WhatsAppChatSessionStatus

    @attribute({
        defaultProvider: () => {
            return {
                prompt: "NO_PROMPT",
                messages: []
            }
        }
    })
    chatHistory: WhatsAppChatHistory



    getLatestMessage(): WhatsAppChatMessage {
        if (this.chatHistory.messages.length === 0) {
            throw new Error("Chat history is empty");
        }
        return this.chatHistory.messages[this.chatHistory.messages.length - 1];
    }

    getSessionPrompt(): string {
        return this.chatHistory.prompt;
    }

    addMessage(message: WhatsAppChatMessage): void {
        this.chatHistory.messages.push(message);
    }

    markSessionInactive(): void {
        this.chatSessionStatus = WhatsAppChatSessionStatus.INACTIVE;
    }
}